from __future__ import annotations

from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
DATA_FILE = DOCS / "data" / "book_projection.yml"
REGISTRY_FILE = ROOT / "registry.yaml"
GITHUB_BLOB = "https://github.com/nfbs2000/speaky-claude-cookbooks/blob/main"
GENERATED = "<!-- This file is generated by scripts/build_pages_docs.py. Do not edit directly. -->\n\n"


def load_yaml(path: Path) -> Any:
    with path.open("r", encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def write(path: Path, body: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GENERATED + body.rstrip() + "\n", encoding="utf-8")


def slug_for_chapter(chapter: dict[str, Any]) -> str:
    return f"{chapter['part_id']}-{chapter['id']}"


def status_class(status: str) -> str:
    return {
        "public": "status-public",
        "public-rewrite": "status-rewrite",
        "partial": "status-partial",
        "omit": "status-omit",
    }[status]


def status_badge(status: str) -> str:
    return f'<span class="projection-status {status_class(status)}">{status}</span>'


def source_link(item: dict[str, str]) -> str:
    path = item["path"]
    title = item.get("title", path)
    full_path = ROOT / path
    if not full_path.exists():
        raise FileNotFoundError(f"Missing cookbook source: {path}")
    return f"[{title}]({GITHUB_BLOB}/{path})"


def official_link(item: dict[str, str]) -> str:
    return f"[{item['title']}]({item['url']})"


def chapter_summary_row(chapter: dict[str, Any]) -> str:
    chapter_link = f"[{chapter['number']} {chapter['title']}](chapters/{slug_for_chapter(chapter)}.md)"
    sources = ", ".join(source_link(item) for item in chapter.get("cookbook", [])[:3])
    if len(chapter.get("cookbook", [])) > 3:
        sources += f" 외 {len(chapter['cookbook']) - 3}개"
    return (
        f"| {chapter_link} | {status_badge(chapter['status'])} | "
        f"{chapter['confidence']} | {sources or '공개 cookbook 대응 없음'} |"
    )


def render_chapter(chapter: dict[str, Any]) -> str:
    cookbook = "\n".join(f"- {source_link(item)}" for item in chapter.get("cookbook", []))
    official = "\n".join(f"- {official_link(item)}" for item in chapter.get("official_docs", []))
    boundaries = "\n".join(f"- {item}" for item in chapter.get("boundary", []))
    practices = "\n".join(f"- {item}" for item in chapter.get("practice", []))
    source_book = chapter.get("source_book", "")

    return f"""# {chapter['number']} {chapter['title']}

{status_badge(chapter['status'])} **신뢰도:** `{chapter['confidence']}`

## 공개 SDK 기준 재작성

{chapter['rewrite']}

## Cookbook 근거

{cookbook or '- 연결할 공개 cookbook 자료가 없습니다.'}

## 공식 문서

{official or '- 공식 문서 직접 대응 없음'}

## 공개 경계

{boundaries or '- 공개 경계 메모 없음'}

## 실습 방향

{practices or '- 관련 cookbook을 먼저 실행하고 관측된 메시지와 tool call을 정리합니다.'}

## 원문 위치

`{source_book}`
"""


def render_part(part: dict[str, Any], chapters: list[dict[str, Any]]) -> str:
    rows = "\n".join(chapter_summary_row(chapter) for chapter in chapters)
    highlights = "\n".join(f"- {item}" for item in part.get("highlights", []))
    return f"""# {part['title']}

{part['summary']}

## 핵심 재배치

{highlights}

## 챕터별 매핑

| 장 | 상태 | 신뢰도 | 주요 cookbook 근거 |
| --- | --- | --- | --- |
{rows}
"""


def render_chapter_map(parts: list[dict[str, Any]], chapters: list[dict[str, Any]]) -> str:
    blocks = ["# 전체 챕터 매핑\n"]
    for part in parts:
        part_chapters = [chapter for chapter in chapters if chapter["part_id"] == part["id"]]
        blocks.append(f"## {part['title']}\n")
        blocks.append("| 장 | 상태 | 신뢰도 | 주요 cookbook 근거 |\n| --- | --- | --- | --- |")
        blocks.extend(chapter_summary_row(chapter) for chapter in part_chapters)
        blocks.append("")
    return "\n".join(blocks)


def render_recipe_index(recipes: list[dict[str, Any]]) -> str:
    cards = []
    for recipe in sorted(recipes, key=lambda item: (item.get("date", ""), item["title"]), reverse=True):
        categories = ", ".join(recipe.get("categories", []))
        authors = ", ".join(recipe.get("authors", []))
        path = recipe["path"]
        cards.append(
            f"""<div class="recipe-card">
<h3><a href="{GITHUB_BLOB}/{path}">{recipe['title']}</a></h3>
<p>{recipe['description']}</p>
<p><strong>분류:</strong> {categories}<br><strong>저자:</strong> {authors}<br><strong>날짜:</strong> {recipe.get('date', '')}</p>
</div>"""
        )
    return "# 전체 레시피\n\n<div class=\"recipe-grid\">\n" + "\n".join(cards) + "\n</div>\n"


def render_categories(recipes: list[dict[str, Any]]) -> str:
    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for recipe in recipes:
        for category in recipe.get("categories", []):
            grouped[category].append(recipe)

    blocks = ["# 카테고리별 레시피\n"]
    for category in sorted(grouped):
        blocks.append(f"## {category}\n")
        for recipe in sorted(grouped[category], key=lambda item: item["title"]):
            blocks.append(f"- [{recipe['title']}]({GITHUB_BLOB}/{recipe['path']}) - {recipe['description']}")
        blocks.append("")
    return "\n".join(blocks)


def render_agent_sdk(recipes: list[dict[str, Any]]) -> str:
    selected = [
        recipe
        for recipe in recipes
        if "Claude Agent SDK" in recipe.get("categories", []) or recipe["path"].startswith("claude_agent_sdk/")
    ]
    blocks = [
        "# Agent SDK 레시피",
        "",
        "공개 SDK 책 투영의 중심 자료입니다. 먼저 `00`부터 `07`까지 순서대로 보고, 필요하면 `agent.py`와 hosting 서버 파일로 내려가면 됩니다.",
        "",
    ]
    for recipe in sorted(selected, key=lambda item: item["path"]):
        blocks.append(f"## [{recipe['title']}]({GITHUB_BLOB}/{recipe['path']})")
        blocks.append("")
        blocks.append(recipe["description"])
        blocks.append("")
        blocks.append(f"- 분류: {', '.join(recipe.get('categories', []))}")
        blocks.append(f"- 날짜: {recipe.get('date', '')}")
        blocks.append("")
    return "\n".join(blocks)


def main() -> None:
    projection = load_yaml(DATA_FILE)
    recipes = load_yaml(REGISTRY_FILE)
    parts = projection["parts"]
    chapters = projection["chapters"]

    for chapter in chapters:
        write(DOCS / "projection" / "chapters" / f"{slug_for_chapter(chapter)}.md", render_chapter(chapter))

    for part in parts:
        part_chapters = [chapter for chapter in chapters if chapter["part_id"] == part["id"]]
        write(DOCS / "projection" / f"{part['id']}.md", render_part(part, part_chapters))

    write(DOCS / "projection" / "chapter-map.md", render_chapter_map(parts, chapters))
    write(DOCS / "recipes" / "index.md", render_recipe_index(recipes))
    write(DOCS / "recipes" / "categories.md", render_categories(recipes))
    write(DOCS / "recipes" / "agent-sdk.md", render_agent_sdk(recipes))


if __name__ == "__main__":
    main()
