#!/usr/bin/env node

import { createHash } from 'node:crypto'
import { promises as fs } from 'node:fs'
import path from 'node:path'

const args = process.argv.slice(2)
const tracePath = path.resolve(requiredValue('--trace'))
const summaryPath = path.resolve(requiredValue('--summary'))
const outputMarkdown = path.resolve(requiredValue('--out-md'))
const outputJson = path.resolve(requiredValue('--out-json'))
const traceText = await fs.readFile(tracePath, 'utf8')
const summaryText = await fs.readFile(summaryPath, 'utf8')
const trace = JSON.parse(traceText)
const summary = JSON.parse(summaryText)

if (trace.chapterSlug !== summary.chapter_id) {
  throw new Error(`chapter_identity_mismatch: ${trace.chapterSlug} != ${summary.chapter_id}`)
}

const claims = trace.events
  .filter((event) => event.eventType === 'assistant.claim')
  .map((event) => ({
    id: event.attributes?.claimId || event.id,
    status: event.attributes?.status || 'unknown',
    evidenceLevel: event.evidenceLevel,
    summary: clean(event.summary),
    sourceRefs: Array.isArray(event.sourceRefs) ? event.sourceRefs : [],
  }))

const publicEvidence = {
  schemaVersion: 'book-sdk-public-evidence-page.v1',
  generatedAt: new Date().toISOString(),
  courseId: trace.courseId,
  chapterSlug: trace.chapterSlug,
  campaignId: summary.campaign_id,
  title: trace.title,
  source: {
    traceId: trace.traceId,
    traceSha256: sha256(traceText),
    summarySha256: sha256(summaryText),
    sourceEventCount: summary.source_event_count,
    publicEventCount: trace.events.length,
    model: summary.actual_models?.[0],
    proofGate: summary.proof_gate,
    secretScan: summary.secret_scan,
  },
  attempts: summary.source_attempts,
  invalidAttempts: summary.invalid_attempts,
  claims,
  replays: replayLinks(trace.chapterSlug, summary.campaign_id),
}

const markdown = renderMarkdown(publicEvidence)
await fs.mkdir(path.dirname(outputMarkdown), { recursive: true })
await fs.mkdir(path.dirname(outputJson), { recursive: true })
await fs.writeFile(outputMarkdown, markdown)
await fs.writeFile(outputJson, `${JSON.stringify(publicEvidence, null, 2)}\n`)
await verify(outputMarkdown, outputJson)

function renderMarkdown(evidence) {
  const attemptRows = evidence.attempts.map((attempt) =>
    `| \`${attempt.attempt_id}\` | \`${attempt.source_chapter_id || evidence.chapterSlug}\` | **${attempt.projection_role || 'replayed'}** | \`${attempt.case_id || 'cross-chapter evidence'}\` | \`${attempt.actual_model}\` | ${attempt.source_event_count} | \`${attempt.raw_sdk_sha256}\` | \`${attempt.raw_process_sha256}\` |`,
  ).join('\n')
  const claimRows = evidence.claims.map((claim) => {
    const status = claimStatusLabel(claim.status)
    return `| \`${claim.id}\` | **${status}** | ${claim.summary} | \`${claim.sourceRefs[0] || '-'}\` |`
  }).join('\n')
  const replayRows = evidence.replays.map((replay) =>
    `| [${replay.label}](${replay.url}) | ${replay.lens} |`,
  ).join('\n')
  const invalid = evidence.invalidAttempts.map((attempt) =>
    `- \`${attempt.attempt_id}\`: ${clean(attempt.reason)} 이 시도는 **invalid attempt**다.`,
  ).join('\n')

  const chapterNumber = evidence.chapterSlug.replace(/^ch0*/, '')
  const observedCount = evidence.claims.filter((claim) => claim.status === 'observed').length
  const correctionCount = evidence.claims.filter(
    (claim) => claim.status === 'correction_required',
  ).length
  const pendingCount = evidence.claims.filter(
    (claim) => claim.status === 'additional_observation_required',
  ).length
  const boundaryRows = evidence.claims
    .filter((claim) => claim.status !== 'observed')
    .map((claim) => `- \`${claim.id}\`: ${claim.summary}`)
    .join('\n')

  return `<!-- Generated by scripts/publish_book_sdk_live_evidence.mjs. -->

# ${chapterNumber}장 실제 Python SDK 관찰

이 페이지는 cookbook 예제를 설명하는 정적 해설이 아니라, Python Claude Agent SDK를 실제
\`${evidence.source.model}\`로 순차 호출해 저장한 공개 증거다. 테스트 assertion은 recorder와
projection 코드의 계약만 검증하며, 아래 판정은 raw SDK message, permission callback, host process
event와 artifact snapshot 중 이 장이 실제로 발생시킨 사건에서 나왔다.

!!! evidence "한 번 수집하고 여러 표면에서 재생"
    원전은 ${evidence.source.sourceEventCount}개 사건이고 공개 projection은 ${evidence.source.publicEventCount}개다.
    credential, private prompt, 비공개 추론 payload, 사용자 절대 경로는 공개하지 않았다. 공개 사건은
    source event ID와 SHA-256을 유지한다.

## 실행 신원

| 항목 | 값 |
| --- | --- |
| campaign | \`${evidence.campaignId}\` |
| model | \`${evidence.source.model}\` |
| proof gate | \`${evidence.source.proofGate}\` |
| secret scan | \`${evidence.source.secretScan}\` |
| raw source / public | **${evidence.source.sourceEventCount} / ${evidence.source.publicEventCount}** |
| observed / correction / more evidence | **${observedCount} / ${correctionCount} / ${pendingCount}** |
| trace SHA-256 | \`${evidence.source.traceSha256}\` |
| summary SHA-256 | \`${evidence.source.summarySha256}\` |

## 무결성 검증된 실제 실행과 보조 출처

| attempt | source chapter | role | case | actual model | source events | raw SDK SHA-256 | host process SHA-256 |
| --- | --- | --- | --- | --- | ---: | --- | --- |
${attemptRows}

\`supporting-only\`는 다른 장이 소유한 원본 실행을 이 장의 claim 출처로만 인용한다는 뜻이다.
그 실행은 이 장의 replay timeline에 다시 삽입하거나 복제하지 않는다.

## 관찰 판정

| claim | 판정 | 실제 관찰 또는 경계 | 첫 source ref |
| --- | --- | --- | --- |
${claimRows}

중요한 판정 규칙은 다음과 같다.

- **관찰됨**: 기대 사건과 순서가 이번 raw evidence에 직접 존재한다.
- **수정 필요**: 같은 버전·설정·도구 범위에서 책 문장과 직접 충돌할 때만 사용한다.
- **추가 관측 필요**: 사건을 유도하지 않았거나 범위가 달라 이번 실행만으로 판단할 수 없다.
- 따라서 **관찰하지 못했다는 사실만으로 책이 틀렸다고 판정하지 않는다.**

## 무효 시도

${invalid || '- 없음'}

## 같은 증거를 보는 공개 표면

| 표면 | 시각화 관점 |
| --- | --- |
${replayRows}

각 표면은 같은 JSON을 무작정 복제한 것이 아니다. Agent Flow는 원인·도구·결과를, Runtime City는
시간축과 실행 구역을, Pixel Agents는 actor 상태를, Observation Ordeal은 주장·선택·결과를
표현한다. 어느 renderer도 raw evidence의 판정을 바꿀 수 없다.

## 공개 경계

${boundaryRows || '- 이 projection에 Missing claim은 없지만, 원문에 기록된 실행 범위 밖 기능까지 일반화하지 않는다.'}

- 공개 JSON: [${evidence.chapterSlug}-live.json](./${evidence.chapterSlug}-live.json)
`
}

function replayLinks(chapterSlug, campaignId) {
  return [
    {
      label: `Agent Flow · ${chapterSlug} 실행`,
      url: `https://nfbs2000.github.io/speaky-agent-flow/education/?collection=book-sdk-ko&run=${chapterSlug}`,
      lens: '원인, tool use/result, permission, claim 경계',
    },
    {
      label: `Runtime City · ${chapterSlug} 실행`,
      url: `https://nfbs2000.github.io/speaky-PGSimCity/education/claude-sdk-runtime-city/?run=book-sdk-ko-${chapterSlug}:${campaignId}`,
      lens: 'OTel 시간축, 실행 zone, Observed/Missing',
    },
    {
      label: `Pixel Agents · ${chapterSlug} 증거`,
      url: `https://nfbs2000.github.io/speaky-pixel-agents/book-sdk-evidence/?chapter=${chapterSlug}`,
      lens: 'actor와 tool lifecycle 상태',
    },
    {
      label: 'Hypnagonia · Observation Ordeal',
      url: `https://nfbs2000.github.io/speaky-hypnagonia/book-sdk-ordeal/?chapter=${chapterSlug}`,
      lens: '검증 주장, 선택, 관찰 consequence',
    },
  ]
}

async function verify(markdownPath, jsonPath) {
  const markdownText = await fs.readFile(markdownPath, 'utf8')
  const jsonText = await fs.readFile(jsonPath, 'utf8')
  const value = JSON.parse(jsonText)
  if (value.source.sourceEventCount <= value.source.publicEventCount) throw new Error('public_evidence_counts_invalid')
  const expectedObserved = summary.claim_statuses.filter((status) => status === 'observed').length
  const expectedPending = summary.claim_statuses.filter(
    (status) => status === 'additional_observation_required',
  ).length
  const expectedCorrection = summary.claim_statuses.filter(
    (status) => status === 'correction_required',
  ).length
  if (value.claims.filter((claim) => claim.status === 'observed').length !== expectedObserved) {
    throw new Error('observed_claim_count_invalid')
  }
  if (value.claims.filter((claim) => claim.status === 'additional_observation_required').length !== expectedPending) {
    throw new Error('pending_claim_count_invalid')
  }
  if (value.claims.filter((claim) => claim.status === 'correction_required').length !== expectedCorrection) {
    throw new Error('correction_claim_count_invalid')
  }
  for (const attempt of value.attempts) {
    if (!markdownText.includes(attempt.attempt_id) || !markdownText.includes(attempt.raw_sdk_sha256)) {
      throw new Error(`attempt_identity_missing: ${attempt.attempt_id}`)
    }
  }
  if (/\/Users\/|sk-ant-|AKIA|CLAUDE_CODE_OAUTH_TOKEN|hidden reasoning/i.test(`${markdownText}\n${jsonText}`)) {
    throw new Error('private_content_detected')
  }
  process.stdout.write(`Verified public Book SDK evidence page with ${value.claims.length} claims\n`)
}

function claimStatusLabel(status) {
  if (status === 'observed') return '관찰됨'
  if (status === 'correction_required') return '범위 수정 필요'
  if (status === 'additional_observation_required') return '추가 관측 필요'
  return status
}

function clean(value) {
  return typeof value === 'string' ? value.replace(/\s+/g, ' ').trim() : ''
}

function sha256(value) {
  return createHash('sha256').update(value).digest('hex')
}

function requiredValue(flag) {
  const value = valueAfter(flag)
  if (!value) throw new Error(`missing_argument: ${flag}`)
  return value
}

function valueAfter(flag) {
  const index = args.indexOf(flag)
  return index >= 0 ? args[index + 1] : undefined
}
